run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - gochecknoglobals
  - exhaustruct
  - varnamelen
linters-settings:
  misspell:
    locale: US
    ignore-words: []