release:
  footer: |
    ## Docker Images
    - `paskalmaksim/service-leader-election:latest`
    - `paskalmaksim/service-leader-election:{{ .Tag }}`
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/service-leader-election:latest
  - paskalmaksim/service-leader-election:{{ .Tag }}
builds:
- dir: ./cmd/
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goos:
  - linux
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'