apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-leader-election
  labels:
    app: service-leader-election
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-leader-election
  template:
    metadata:
      labels:
        app: service-leader-election
    spec:
      serviceAccountName: service-leader-election
      containers:
      - name: service-leader-election
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 28086
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 28086
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
