apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-leader-election
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /debug
        pathType: Prefix
        backend:
          service:
            name: service-leader-election
            port:
              number: 28086