apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-leader-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-leader-election-role
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-leader-election
roleRef:
  kind: Role
  name: service-leader-election-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: service-leader-election
  namespace: {{ .Release.Namespace }}